AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Conference Room Booking System (Free Tier)

# -------------------------------------------------------------------------
# GLOBAL SETTINGS
# These settings apply to all 5 Lambda functions automatically.
# -------------------------------------------------------------------------
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x
    Architectures: [x86_64]
    MemorySize: 128
    Environment:
      Variables:
        # Database Tables
        LOCATIONS_TABLE: !Ref LocationsTable
        ROOMS_TABLE: !Ref ConferenceRoomsTable
        BOOKINGS_TABLE: !Ref BookingsTable
        PRICING_TABLE: !Ref PricingRulesTable
        # Integration Links
        WEATHER_FUNC_NAME: !Ref WeatherService
        PAYMENTS_QUEUE_URL: !Ref PaymentsQueue
        REFUNDS_QUEUE_URL: !Ref RefundsQueue
        BOOKINGS_TOPIC_ARN: !Ref BookingsTopic

Resources:
  # =========================================================================
  # 1. INGRESS & AUTHENTICATION
  # =========================================================================
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: ConferenceApi
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: conference-users
      AutoVerifiedAttributes: [email]
      Schema: [{Name: email, AttributeDataType: String, Mutable: true}]

  CognitoClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: web-client
      GenerateSecret: false

  ApiAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuth
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      ProviderARNs: [!GetAtt CognitoUserPool.Arn]
      RestApiId: !Ref ApiGateway

  # =========================================================================
  # 2. DATA LAYER (DynamoDB & S3)
  # NOTE: BillingMode is PROVISIONED to ensure FREE TIER eligibility.
  # =========================================================================
  LocationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: locations
      AttributeDefinitions: [{AttributeName: id, AttributeType: S}]
      KeySchema: [{AttributeName: id, KeyType: HASH}]
      BillingMode: PROVISIONED
      ProvisionedThroughput: {ReadCapacityUnits: 5, WriteCapacityUnits: 5}

  ConferenceRoomsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: conference_rooms
      AttributeDefinitions: [{AttributeName: id, AttributeType: S}]
      KeySchema: [{AttributeName: id, KeyType: HASH}]
      BillingMode: PROVISIONED
      ProvisionedThroughput: {ReadCapacityUnits: 5, WriteCapacityUnits: 5}

  BookingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: bookings
      AttributeDefinitions: [{AttributeName: id, AttributeType: S}]
      KeySchema: [{AttributeName: id, KeyType: HASH}]
      BillingMode: PROVISIONED
      ProvisionedThroughput: {ReadCapacityUnits: 5, WriteCapacityUnits: 5}

  PricingRulesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: pricing_rules
      AttributeDefinitions: [{AttributeName: id, AttributeType: S}]
      KeySchema: [{AttributeName: id, KeyType: HASH}]
      BillingMode: PROVISIONED
      ProvisionedThroughput: {ReadCapacityUnits: 5, WriteCapacityUnits: 5}

  S3ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "conf-images-${AWS::AccountId}"
      CorsConfiguration:
        CorsRules: [{AllowedHeaders: ["*"], AllowedMethods: [GET], AllowedOrigins: ["*"]}]

  # =========================================================================
  # 3. DECOUPLING (SQS & SNS)
  # =========================================================================
  PaymentsQueue:
    Type: AWS::SQS::Queue
  RefundsQueue:
    Type: AWS::SQS::Queue
  BookingsTopic:
    Type: AWS::SNS::Topic

  # =========================================================================
  # 4. MICROSERVICES (Lambda Functions)
  # =========================================================================
  
  # --- Service 1: Weather (Synchronous) ---
  WeatherService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/weather/
      Handler: app.handler
      Events:
        GetWeather:
          Type: Api
          Properties: {Path: /weather, Method: get, RestApiId: !Ref ApiGateway}

  # --- Service 2: Booking (Orchestrator) ---
  BookingService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/booking/
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy: {TableName: !Ref BookingsTable}
        - DynamoDBReadPolicy: {TableName: !Ref ConferenceRoomsTable}
        - DynamoDBReadPolicy: {TableName: !Ref PricingRulesTable}
        - LambdaInvokePolicy: {FunctionName: !Ref WeatherService}
        - SQSSendMessagePolicy: {QueueName: !GetAtt PaymentsQueue.QueueName}
      Events:
        CreateBooking:
          Type: Api
          Properties:
            Path: /book
            Method: post
            RestApiId: !Ref ApiGateway
            Auth: {Authorizer: !Ref ApiAuthorizer}
        GetStatus:
          Type: Api
          Properties:
            Path: /book/{id}
            Method: get
            RestApiId: !Ref ApiGateway
            Auth: {Authorizer: !Ref ApiAuthorizer}

  # --- Service 3: Financial (Async Processor) ---
  FinancialService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/financial/
      Handler: app.handler
      Policies:
        - DynamoDBWritePolicy: {TableName: !Ref BookingsTable}
        - SNSPublishMessagePolicy: {TopicName: !GetAtt BookingsTopic.TopicName}
      Events:
        PaymentTrigger:
          Type: SQS
          Properties: {Queue: !GetAtt PaymentsQueue.Arn, BatchSize: 1}

  # --- Service 4: Notification (Async Emailer) ---
  NotificationService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/notification/
      Handler: app.handler
      # NOTE: You must verify your email in SES console for this policy to work
      Policies:
        - SESCrudPolicy: {IdentityName: "YOUR_VERIFIED_EMAIL@example.com"} 
      Events:
        NotifyTrigger:
          Type: SNS
          Properties: {Topic: !Ref BookingsTopic}

  # --- Service 5: Refund (Async Trigger) ---
  RefundService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/refund/
      Handler: app.handler
      Policies:
        - SQSSendMessagePolicy: {QueueName: !GetAtt RefundsQueue.QueueName}
      Events:
        CreateRefund:
          Type: Api
          Properties:
            Path: /refund
            Method: post
            RestApiId: !Ref ApiGateway
            Auth: {Authorizer: !Ref ApiAuthorizer}

Outputs:
  ApiUrl:
    Description: "API Gateway URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref CognitoUserPool
  ClientId:
    Description: "Cognito Client ID"
    Value: !Ref CognitoClient